### PR TITLE
added Apache repository for Apache Cassandra

### PR DESCRIPTION
**Pull request by VMelandri**
As per title :)

### CODE REVIEW

**Comment by VMelandri** [comment]
Your build ran 111 tests in RSpec with 0 failures, why does it say failed? :/

**Comment by dallinb** [comment]
Hi,

Thank you very much for this merge request, but this was already being covered (almost identically) on this branch https://github.com/locp/cassandra/tree/feature-351.

The tests are failing because Puppet Labs have deprecated a setting in the metadata so that is failing (fixed in 9b9545e of this module).  Also this module requires 100% test coverage so that is also failing.  Please see https://circleci.com/gh/locp/cassandra/2020 for details of a successful build.

**Comment by VMelandri** [comment]
Oh well too bad. I should have committed this sooner, was sitting in my workspace for about a month (I needed cassandra >=3.9) :)
Did not look into pending PR as 'feature 351' meant nothing to me

**Comment by dallinb** [comment]
Funnily enough it's taking me ages to get this to anywhere near releasable, but almost there.  Will make an effort to make branches more specific and have better names in future.

Thanks again though.

**Comment by tibers** [comment]
If you want to call out specific issues which are pain points, mention them
in gitter. ;)

**Pull request closed without merging**
