### PR TITLE
attemping to realize client security

### PR DESCRIPTION
**Pull request by tibers**

### CODE REVIEW

**Comment by dallinb** [comment]
Joshua,

Thanks again.  I'll add in some spec/unit tests to cover this.  I've also updated (on that branch, see https://github.com/locp/cassandra/blob/pull/235/client_security/CONTRIBUTING.md) the contributing material.  This should help you setup your environment (including puppet-lint) to be able to at least run the unit tests.  If the documentation is unclear, please let me know and I will try and clarify it.

Best wishes,

Ben

**Comment by dallinb** [comment]
Joshua,

I've merged this into a branch I'm working on it.  It's good for now and I need to write spec/unit tests around your contribution.  Please hold off any further for now.

Ben

**Comment by tibers** [comment]
That's the last one, I swear. ;)

**Comment by dallinb** [comment]
No worries.  Thanks again.

**Comment by dallinb** [comment]
Now need to work on the beaker/acceptance tests which will actually try this stuff out on docker containers.

**Comment by tibers** [comment]
I'm actually not sure how that stuff works but if you point me towards
decent docs I'll try to pick it up for the next go.

**Comment by dallinb** [comment]
Sorry dude, it was only a note for myself.  It is something that I need to do.  You can then see how to generate acceptance tests using beaker that will test the new changes against the operating systems that this module supports.

**Comment by dallinb** [comment]
OK, that's this completed.  I'll be merging this into master when the next release is being build which should be in the next week or two.

**Comment by dallinb** [comment]
You can see the result of the tests on Debian 7 at https://circleci.com/gh/locp/cassandra/780 under the **./scripts/circle.bash acceptance_tests** section.

**Pull request merged**
